// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxngbzitmzvvulrlgidn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4bmdieml0bXp2dnVscmxnaWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NjkzMTQsImV4cCI6MjA4NDM0NTMxNH0.acot-WKGa4oXpJoI2YOlpljBMvQnD2L6sURhw4hD2iM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});